---
- name: Create SSH users list
  set_fact:
    ssh_users_keys: |
      {% set res = [] -%}
        {% for host_name in ssh_list -%}
          {% for host_user_name in host_name -%}
            {% for user_name in host_name[host_user_name]| replace(' ', '')| split(',') -%}
              {% set ignored = res.extend([{ "user_name": user_name, "host_user": host_user_name }]) -%}
            {%- endfor %}
          {%- endfor %}
        {%- endfor %}
      {{ res }}

- name: Set up authorized keys
  authorized_key:
    user: "{{item.host_user}}"
    state: present
    key: "{{ ssh_keys_list[item.user_name] }}"
  loop: "{{ ssh_users_keys }}"
  become: yes
