---
- name: Get host SSH list from vault
  set_fact:
    ssh_list: "{{ lookup('hashi_vault', 'secret=cloud/data/{{ vault_folder }}/ssh/' + 'shared_list')  | default({}) }},
                {{ lookup('hashi_vault', 'secret=cloud/data/{{ vault_folder }}/ssh/' + inventory_hostname, errors='warn') | default({}) }}"

- debug:
    msg: "{{ ssh_list }}"

- name: debug
  debug:
    msg: "cloud/data/ec2/ansible-config/{{ customer_name }}-{{ customer_project }}-{{ environment_name }}"

- name: Get ansible config
  set_fact:
    ansible_config: "{{ lookup('hashi_vault', 'secret=cloud/data/ec2/ansible-config/{{ customer_name }}-{{ customer_project }}-{{ environment_name }}', errors='warn') | default('no-config', true)}}"

- name: Create SSH users list
  set_fact:
    ssh_users_list: |
      {% set res = [] -%}
        {% for host_name in ssh_list -%}
          {% for host_user_name in host_name -%}
            {% for user_name in host_name[host_user_name]| replace(' ', '')| split(',') -%}
              {% set ignored = res.extend([user_name]) -%}
            {%- endfor %}
          {%- endfor %}
        {%- endfor %}
      {{ res | select() | unique }}

- name: Get users ssh keys
  set_fact:
    ssh_keys_list: "{{ ssh_keys_list| default({})| combine ({ item: lookup('hashi_vault', 'secret=cloud/data/users/' + item )['ssh_key']} | default({})) }}"
  with_items: "{{ ssh_users_list }}"
