name: "Plan on Comment"

on:
  issue_comment:
    types: [created]

jobs:
  plan:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && github.event.issue.state == 'open' && contains(github.event.comment.body, 'gautam-plan')
    steps:
      - name: Run start plan 
        shell: bash
        id: initial_sha
        run: |
          echo "Action is starting"
      
      - name: Display PR Number
        shell: bash
        run: |
          echo "Pull Request Number: ${{ github.event.issue.number }}" 
      
      - name: Get running Actions list
        uses: actions/github-script@v3 
        with:
          script: | 
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              status: 'in_progress',
              event: 'issue_comment'
            }
            try{ 
              const result = await github.actions.listWorkflowRunsForRepo(request)
              workflows = result.data.workflow_runs
              console.log(JSON.stringify(result.data, null, 2));
            }catch (err){
              console.log("Error : ", err)
              core.setFailed(`Request failed with error ${err}`)
            }

      - name: Run sleep plan 
        shell: bash
        run: |
          sleep 15
      
      - name: Run sleep plan 
        shell: bash
        run: |
          sleep 15
          
      - name: Run stop job 
        shell: bash
        run: |
          echo "Thread is done"
            