name: "Plan on Comment"

on:
  issue_comment:
    types: [created]

jobs:
  plan:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'gautam-plan')
    steps:
      - name: Check if PR is open
        run: |
            if [ "${{ github.event.issue.pull_request.state }}" != "open" ]; then
                echo "PR is not open. Skipping workflow."
                exit 1
            fi

      - name: Comment Runner logs location
        uses: actions/github-script@v3 
        with:
          script: |
            const commentBody = '**gautam-plan is in running.. \nTo see realtime logs of Plan visit** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
            await github.issues.createComment({
              owner:  context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: commentBody
            });
            