name: "Plan on Comment"

on:
  issue_comment:
    types: [created]

jobs:
  plan:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && github.event.issue.state == 'open' && contains(github.event.comment.body, 'gautam-plan')
    steps:
      - name: Run start plan 
        shell: bash
        run: |
          echo "Action is starting"


      - name: Run sleep plan 
        shell: bash
        run: |
          sleep 15
      
      # - name: Comment Runner logs location
      #   uses: actions/github-script@v3 
      #   with:
      #     script: |
      #       const commentBody = '**gautam-plan is in progress.. \nTo see realtime logs of Plan visit** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
      #       await github.issues.createComment({
      #         owner:  context.repo.owner,
      #         repo: context.repo.repo,
      #         issue_number: context.issue.number,
      #         body: commentBody
      #       });

      - name: Get running Actions list
        uses: actions/github-script@v3 
        with:
          script: | 
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              status: 'in_progress'
            }
            try{ 
              const result = await github.actions.listWorkflowRunsForRepo(request)
              console.log(JSON.stringify(result.data, null, 2));
            }catch (err){
              console.log("Error : ", err)
              core.setFailed(`Request failed with error ${err}`)
            }
      
      - name: Run sleep plan 
        shell: bash
        run: |
          sleep 15
          
      - name: Run stop job 
        shell: bash
        run: |
          echo "Thread is done"
            